spring.application.name=suscripciones

spring.threads.virtual.enabled=true

management.endpoints.web.exposure.include=health,info,prometheus

management.endpoint.health.show-details=always

management.prometheus.metrics.export.enabled=true

management.endpoint.prometheus.enabled=true

management.endpoints.web.base-path=/actuator