spring.application.name=subcripciones

logging.file.name=logs/app.log

logging.level.root=INFO

logging.level.com.empresa.app=DEBUG

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

management.endpoints.web.exposure.include=prometheus,health,info