name: "CD: Build, Push to ECR & Deploy to ECS"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build-and-deploy:
    name: "Build Docker Image & Deploy to AWS Academy"
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Set up JDK 21"
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: "Configurar credenciales AWS Academy"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          aws-region: us-east-1 #

      - name: "Login en Amazon ECR"
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: "Build and Push Image to ECR"
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest
            ${{ secrets.ECR_REPO_URL_FRONTEND }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "Descargar Task Definition actual desde AWS"
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ secrets.ECS_TASK_DEFINITION_NAME }} \
            --query taskDefinition > task-definition.json

      - name: "Actualizar Tag de la imagen en la Task Def"
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: suscripciones-container 
          image: ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest

      - name: "Desplegar nueva Task Definition en el Servicio ECS"
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE_NAME }}
          cluster: ${{ secrets.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true 