name: CI/CD Pipeline - ECS Deploy Multicontenedor

on:
  push:
    branches: [ "main" ]  # Se activará automáticamente cuando hagas push a la rama main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código del repositorio en el runner de GitHub
      - name: Checkout código
        uses: actions/checkout@v4

      # 2. Configurar las credenciales para conectarse a AWS
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # Se ignora automáticamente si está vacío
          aws-region: us-east-1

      # 3. Autenticar Docker con tu Amazon ECR
      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Construir la imagen de tu Backend (Java Spring Boot) y subirla a ECR
      - name: Build imagen y push a ECR
        run: |
          docker build -t suscripciones-backend .
          docker tag suscripciones-backend:latest 864092060431.dkr.ecr.us-east-1.amazonaws.com/buh-repositorio-ecc:latest
          docker push 864092060431.dkr.ecr.us-east-1.amazonaws.com/buh-repositorio-ecc:latest

      # 5. Inyectar la nueva imagen de ECR dentro de tu archivo 'task-definition.json'
      - name: Actualizar Tag de la imagen en la Task Def
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: suscripciones-container # Debe coincidir con el name en tu JSON
          image: 864092060431.dkr.ecr.us-east-1.amazonaws.com/buh-repositorio-ecc:latest

      # 6. Desplegar la actualización en tu clúster de ECS
      # ¡IMPORTANTE!: Reemplaza 'TU_CLUSTER_NAME' y 'TU_SERVICE_NAME' con los nombres reales de tu consola
      - name: Desplegar nueva Task Definition en el Servicio
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: suscripciones-buh-service # El nombre que le diste al crear el servicio en ECS
          cluster: cluster-buh-ecc          # El nombre de tu clúster de la captura anterior
          wait-for-service-stability: true